### ISSUE TITLE
Loader typescript chain in AOT ?

### ISSUE THREAD

**Issue by kekel87** [shlomiassaf/ngc-webpack#41]
We use an internal loader to remove dev code for produciton build (like console.log and internal logger) applied to typescript files :
```javascript
// webpack.prod.js
...
{
    enforce : 'pre',
    test : /\.ts$/,
    loaders : ['internal-replace-loader'],
    exclude : [/\.(spec|e2e)\.ts$/]
},
...
{
    test : /(?:\.ngfactory\.js|\.ngstyle\.js|\.ts)$/,
    use : ['@angular-devkit/build-optimizer/webpack-loader', '@ngtools/webpack']
},
...
```
In JIT , build loader chain works fine, but in AOT this loader is call but code remplacement is not applied to the output build.

Do you have an idea ?
Thanks

**Comment by shlomiassaf** [comment]
You can't use a loader before `@ngtools/webpack` because `@ngtools/webpack` load's the TS file from the filesystem and does not use the source webpack pass to it.

Instead, you need to use custom transformers (TypeScript transformation API).
`@ngtools/webpack` does not allow adding custom transformers but `ngc-webpack` does.

Add them through the options (see [API](https://github.com/shlomiassaf/ngc-webpack/blob/master/src/plugin-options.ts#L74))

**Comment by kekel87** [comment]
Thank you, I have already watched the API.

I will choose this solution, is it better to use `readFileTransformer` or `tsTransformers` in my case?

Hopefully `@ngtools/webpack` will use the loader chain one day in AOT.
