### ISSUE TITLE
Is it possible to inline html and styles in js files generated by ngc-w (not only the final bundled js)?

### ISSUE THREAD

**Issue by tinesoft** [shlomiassaf/ngc-webpack#7]
Hi @shlomiassaf ,

Thanks for this great project! 

I'm publishing a angular library, with components with external `*.html` templates and `*.scss` styles, referenced via `templateUrl `and `stylesUrls `:
```
templateUrl './my-html',
stylesUrls: ['/.my-style.scss']
```

With `webpack`, I'm able to successfully generate a `UMD` js bundle of the library, that contains everything inlined (template and styles).

I would like to achieve the same with the js files generated by `ngc-w` (via `ngc`), because i am also releasing them as part of my library (along with the `*.d.ts`, `*.metadata.json`, and `*.js.map` for AoT compatibility) .

Is it possible to achieve that with your library, coupled with webpack?

Here are the relevant part of my configuration:

**webpack.config.js**
```
//Config
module.exports = {
  devtool: 'source-map',
  entry: helpers.root('src/index.ts'),

  resolve: {
    modules: [
      'node_modules',
      helpers.root('src')
    ],
    extensions: ['.ts', '.js']
  },

  context: helpers.root('src'),

  module: {
    loaders: [
      {
        test: /\.ts$/,
        use: [
          {
            loader: 'awesome-typescript-loader',
            query: {
              configFileName: helpers.root('tsconfig-aot.json')
            }
          },
          'angular2-template-loader'
        ],
        exclude: [/\.(spec|e2e)\.ts$/]
      },
      {
        test: /\.html$/,
        use: ['raw-loader']
      },
      {
        test: /\.css$/,
        use: ['raw-loader', 'css-loader?importLoaders=1', 'postcss-loader']
      },
      {
        test: /\.(scss|sass)$/,
        exclude: helpers.root('src', 'scss'),
        use: ['raw-loader', 'css-loader?importLoaders=1', 'postcss-loader', 'sass-loader']
      }
    ]
  },
 output: {
    path: helpers.root('dist/bundles'),
    filename: 'my-library.umd.js',
    library: 'my-library',
    libraryTarget: 'umd',
    umdNamedDefine: true
  },

  plugins: [
    new NgcWebpack.NgcWebpackPlugin({
      disabled: false,
      tsConfig: helpers.root('tsconfig-aot.json'),
      resourceOverride: helpers.root('config/resource-override.js')
    }),
    new webpack.optimize.UglifyJsPlugin({ // https://github.com/angular/angular/issues/10618
      beautify: false,
      mangle: {
        screw_ie8: true,
        keep_fnames: true
      },
      compress: {
        warnings: false,
        screw_ie8: true
      },
      comments: false,
      sourceMap: true
    })
  ]
}
```

**tsconfig.json ( AoT compatible)***
```
{
    "compilerOptions": {
        "target": "es5",
        "module": "es6",
        "lib": [
            "es6",
            "dom"
        ],
        "moduleResolution": "node",
        "declaration": true,
        "experimentalDecorators": true,
        "baseUrl": ".",
        "stripInternal": true,
        "outDir": "./dist",
        "rootDir": "./src",
        "sourceMap": true,
        "inlineSources": true,
        "skipLibCheck": true,
        "typeRoots": [
            "node_modules/@types"
        ]
    },
    "files": [
        "./src/index.ts"
    ],
    "exclude": [
        "node_modules",
        "dist",
        "demo",
        "config",
        "coverage",
        "src/**/*.spec.ts"
    ],
    "angularCompilerOptions": {
        "strictMetadataEmit": true,
        "genDir": "./dist/ngfactories"
    }
}
```

I'm using 
`"ngc-webpack": "1.1.0"` ( i'm limited to angular `2.3.1`)
` "typescript": "2.0.2",`
` "webpack": "2.2.0"`

Thanks in advance!

**Comment by shlomiassaf** [comment]
@tinesoft Hi,

This is not really related to the plugin but more a general question about webpack, angular and library distribution...

When you publish a library you need to remember that people are using with **with** and **without** AOT.

You need to provide a distribution that supports both, this means having all inline resources (template/styles) inlined in the code as well as supply all the resources as files.

Inlined: For JIT
Supplied: For AOT

The `metadata.json` files that the compiler creates will reference those supplied code for AOT compilation of you library with applications that use it.

Now, you also need to understand the role of webpack in the process...
Webpack creates the UMD bundle, that's it. It does not create the ES modules. Since a UMD is a bundle, like any other application, you get the resources inlined.

The ES modules are created by typescript.  
Your `tsconfig` sets `"outDir": "./dist"` and this is where the ES modules distribution comes from. The angular compiler does not emit `ngFactory`/`styles`/ etc... files to `dist` and this is how it should be, it will only emit `metadata.json` files which are used when these files are compiled by an application... the logic is simple, the application using your library needs to be compiled but you can't compile the same source code twice so you distribute NON-AOT compiled source code but with AOT metadata so it can be compiled (metadata is needed since type information is lost).

To recap, TypeScript compiles the files, AOT compiler just adds metadata files, no change to the files and no extra source code!

Since TypeScript compiles the files you end up with a `templateUrl` tag without any change, just a simple string (e.g.: `./my-component.html`) - webpack is not there...

for AOT support you just need to add a webpack copy plugin that copies all the files you need to the `dist` dir (html/css/etc). Since `metadata.json` files reference them and they are present they will be used in the AOT compilation process on application using your library.

For JIT it is not that trivial... you need a process that traverses the source code and looks for these resources and replaces them with the inlined version.

You need to be careful here not to relay things you are used to from webpack loaders, for example lazy routes via `loadChildren` needs a webpack loader... (though 0% change they are used in a lib, just for the demonstration)

Another common use case is postCSS plugins (auto prefixing, etc...), you'll get a different result from webpack if you use them.

You need something that does the above (gulp plugin maybe) but it won't be perfect.

It is possible to use webpack for this task, but it requires a new plugin and some logic...

**Comment by tinesoft** [comment]
Hi @shlomiassaf 

Thank you for this detailed answer. Very informative 👍 
I'm already using a combinaison of `ngc` + `gulp` to publish my library in a way that works
for both AoT and JiT compilations. I thought there was a simpler way to achive this using with your plugin and webpack combined...

Anyway, thanks for your help!

**Comment by cgatian** [comment]
@tinesoft have you found a better approach to UMD bundling?

**Comment by tinesoft** [comment]
Hi @cgatian ,

Well i continued using my `gulp `+ `ngc `combinaison to achieve this. Thanks to this plugin [gulp-inline-ng2-template](https://www.npmjs.com/package/gulp-inline-ng2-template) i can inline the *.html and styles into my components. Then i run `ngc` from gulp on the inlined components generated earlier, to generate the library  files (`*.d.ts`, `*.metadata.json`, ...)  for AoT compatibility.

You can have a look on this [project](https://github.com/MurhafSousli/ng2-sharebuttons) i'm contributing to.

I plan on releasing this into a yeoman generator soon. If you're interested, i'll post back here when it is done.


Cheers!

**Comment by cgatian** [comment]
Darn. Was hoping there was one solution to it. I'm also doing the same.

**Comment by azhukaudev** [comment]
@cgatian you can take a look at this [library starter kit](https://github.com/lexzhukov/ng-library-starter-kit).
